apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: anchor

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Say hello 
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: | 
          echo "hello world"
      - name: hello2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: | 
          echo "hello world"
