apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: anchor 3

on:
  workflow_dispatch:

jobs:
  hello1:
    steps: 
      - &hello_steps
        name: Say hello 
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: | 
          echo "hello world"

  hello2:
    steps: 
      - <<: *hello_steps
        run: |
          echo "hello 2"
